### ISSUE TITLE
Will it support CHN region?

### ISSUE THREAD

**Issue by MelonGx** [mariohackandglitch/kartdlphax#2]
I have 2 CHN consoles to be available to do any test.
The CHN MK7 is 00040000 0008B500.
Current kartdlphax said it's not compatible with this title, but CHN MK7 should have the same contents as JPN USA EUR since it integrates v1.1 patch.

**Comment by HotoRas** [comment]
Same comes to KOR MK7. (00040000 00030A00)
I think the reason is that it's not defined (check out /plugin/includes and /3ds_ropkit), and I think it's because it's not analyzed or there's no dump.
I made a dump with my device (I have two and both are done broken and not bricked though), and I can provide you if you want- encrypted or decrypted, `.3ds` or `.cia`.

**Comment by raketaro** [comment]
mine is KOR MK7 too!

(wow my first comment)

**Comment by PabloMK7** [comment]
#12
